apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: ZGF0YWJhc2UtMS5jd3YweTRza3dmam4udXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
  db_username: YWRtaW4=
  db_password: ZGF0YWJhc2UtMQ==
